### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Bdbmzwsc** [xianyongjian080402/Minecraft-Optimal-Starter_3#7]
### 开始之前……

- [X] 我已经认真阅读[说明文件(Githib)](https://github.com/xianyongjian080402/Minecraft-Optimal-Starter_2/blob/master/.github/ISSUE_TEMPLATE/ISSUE_GUIDELINES.md)/[说明文件(Gitee)](https://gitee.com/xian66/minecraft-optimal-starter_2/blob/master/.gitee/ISSUE_GUIDELINES.md)

### Bug描述

i got a error message when mos initialize on macos
error message:

### 复现方法(重现步骤)

nothing,just wait

### 期望的效果

no error message

### 实际效果

got a error message

### 日志

```
Traceback (most recent call last):
  File "/Users/bdbmzwsc/develop/Minecraft-Optimal-Starter_3/Code/MainWindow.py", line 417, in RunInitialize
    Settings_()
  File "/Users/bdbmzwsc/develop/Minecraft-Optimal-Starter_3/Code/MainWindow.py", line 358, in Settings_
    self.Json_MOS = JsonRead(self.JsonFile)
  File "/Users/bdbmzwsc/develop/Minecraft-Optimal-Starter_3/Code/Code.py", line 13, in JsonRead
    r = json.load(f)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
fish: Job 1, 'python3 ./main.py' terminated by signal SIGABRT (Abort)
```

**Comment by Bdbmzwsc** [comment]
so when will u merge pr

**Comment by David-Xian66** [comment]
https://github.com/xianyongjian080402/Minecraft-Optimal-Starter_3/pull/8

**Comment by David-Xian66** [comment]
已合并  感谢内部成员
@Bdbmzwsc @HeimNad
